"""
Django settings for odozi project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b%qzdyvx!qapu)dok06xh)ydevyxl*ee(ae)y#^12&02=qp+p6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "quiet-women-shake.loca.lt",
]

# CORS
CORS_ALLOWED_ORIGINS = ["http://localhost:5501", "http://127.0.0.1:5501", 
                        "http://127.0.0.1:8000",'http://127.0.0.1',
                        "ws://127.0.0.1:8000", "ws://localhost:8000"]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',

    # apps
    'account_profile',
    'django_python',

    # 3rd party
    'rest_framework',
    'django.contrib.sites',
    'rest_framework.authtoken',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth.socialaccount.providers.github',
    'corsheaders',
    'channels',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'odozi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",

        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'odozi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

SITE_ID = 1

# Configure DRF to use JWT and dj-rest-auth settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ],
}
# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# GitHub-Only Constraints (Add to settings.py)
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'SCOPE': ['user', 'repo', 'read:org'],
    }
}

# 1. Use a custom adapter to block password-based registration only
ACCOUNT_ADAPTER = 'account_profile.NoPasswordRegistrationAdapter.NoPasswordRegistrationAdapter'

# 2. Allauth Core Setup
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "none" # Change to "mandatory" or "optional" later if needed

# 3. Handle GitHub Handshake Automatically
SOCIALACCOUNT_AUTO_SIGNUP = True

# 4. Django REST Framework & JWT Configuration
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'my-app-auth'          # Stores access token in cookie
JWT_AUTH_REFRESH_COOKIE = 'my-refresh'   # Stores refresh token in cookie
JWT_AUTH_HTTPONLY = True                 # Protects against XSS attacks
JWT_AUTH_SECURE = True                   # Enforces HTTPS (Set to False ONLY during local development)



GITHUB_APP_CLIENT_SECRET = config('GITHUB_APP_CLIENT_SECRET')
TOKEN_ENCRYPTION_KEY = config('TOKEN_ENCRYPTION_KEY')
ODOZI_APP_ID = config('ODOZI_APP_ID')
ODOZI_WEBHOOK_SECRET = config('ODOZI_WEBHOOK_SECRET')
GITHUB_INSTALLATION_ID = config('GITHUB_INSTALLATION_ID')


STATIC_URL = 'static/'

CELERY_BROKER_URL = "redis://localhost:6379/0"

CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'





# 1. Store the exact local file path configuration
PROJECT_ROOT = BASE_DIR.parent

PRIVATE_KEY_PATH = os.path.join(PROJECT_ROOT, "odozy-ci-agent.2026-05-17.private-key.pem")
# 2. Open and read the file text data into memory securely
if os.path.exists(PRIVATE_KEY_PATH):
    print("part66")
    with open(PRIVATE_KEY_PATH, "r", encoding="utf-8") as key_file:
        GITHUB_APP_PRIVATE_KEY = key_file.read()
else:
    # Fallback to prevent server crashes if the file isn't found locally
    GITHUB_APP_PRIVATE_KEY = ""



yaml_file_path = os.path.join(BASE_DIR, 'agents', 'orchestrator.yaml')
print(yaml_file_path)

ASGI_APPLICATION = 'odozi.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
