"""
Django settings for odozi project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import datetime
from pathlib import Path
import os
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b%qzdyvx!qapu)dok06xh)ydevyxl*ee(ae)y#^12&02=qp+p6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "fast-results-behave.loca.lt",
    "short-aliens-sniff.loca.lt",
    "odozi.onrender.com",
    "https://odozi.vercel.app"
]

# CORS
CORS_ALLOWED_ORIGINS = ["http://localhost:5501", "http://127.0.0.1:5501", "http://localhost:5173",
                        "http://127.0.0.1:8000",'http://127.0.0.1',"http://127.0.0.1:5173", "https://odozi.vercel.app",
                        "ws://127.0.0.1:8000", "ws://localhost:8000", "https://fast-results-behave.loca.lt"]

CORS_ALLOW_CREDENTIALS = True

# 4. CRITICAL: Allow cookies to travel across different domains/ports
# Changing this to 'None' breaks the barrier and allows cross-site cookie drops
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = "None"

# 5. WARNING: Browsers WILL REJECT SameSite="None" cookies unless they are Secure (HTTPS).
# However, browsers make a special exception for 'localhost' and '127.0.0.1' over HTTP.
# To be completely safe during local testing, set these to False.

# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',

    # apps
    'account_profile',
    'django_python',
    'general',

    # 3rd party
    'rest_framework',
    'rest_framework_simplejwt',
    'django.contrib.sites',
    'rest_framework.authtoken',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth.socialaccount.providers.github',
    'corsheaders',
    'channels',
    'django_user_agents',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'odozi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",

        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'odozi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        "OPTIONS": {
            "timeout": 30, 
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

SITE_ID = 1

# Configure DRF to use JWT and dj-rest-auth settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ],
}
# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# GitHub-Only Constraints (Add to settings.py)
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'SCOPE': ['user', 'repo', 'read:org'],
    }
}

# 1. Use a custom adapter to block password-based registration only
ACCOUNT_ADAPTER = 'account_profile.NoPasswordRegistrationAdapter.NoPasswordRegistrationAdapter'

# 2. Allauth Core Setup
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "none" # Change to "mandatory" or "optional" later if needed

# 3. Handle GitHub Handshake Automatically
SOCIALACCOUNT_AUTO_SIGNUP = True

# 4. Django REST Framework & JWT Configuration
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'my-app-auth'          # Stores access token in cookie
JWT_AUTH_REFRESH_COOKIE = 'my-refresh'   # Stores refresh token in cookie
JWT_AUTH_HTTPONLY = True                 # Protects against XSS attacks
JWT_AUTH_SECURE = True                   # Enforces HTTPS (Set to False ONLY during local development)



GITHUB_APP_CLIENT_SECRET = config('GITHUB_APP_CLIENT_SECRET')
TOKEN_ENCRYPTION_KEY = config('TOKEN_ENCRYPTION_KEY')
ODOZI_APP_ID = config('ODOZI_APP_ID')
ODOZI_WEBHOOK_SECRET = config('ODOZI_WEBHOOK_SECRET')
GITHUB_INSTALLATION_ID = config('GITHUB_INSTALLATION_ID')
GITHUB_CLIENT_ID = config('GITHUB_CLIENT_ID')
GEMINI_API_KEY = config("GEMINI_API_KEY")
CLOUDINARY_CLOUD_NAME = config("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = config("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = config("CLOUDINARY_API_SECRET")

# The public Django origin used in links sent from asynchronous Celery tasks.
# Set PUBLIC_API_BASE_URL to your HTTPS/tunnel URL when deploying.
PUBLIC_API_BASE_URL = config("PUBLIC_API_BASE_URL", default="http://127.0.0.1:8000").rstrip("/")





STATIC_URL = 'static/'

# Development keeps the existing local Redis layout. Production uses the
# managed Redis connection supplied in REDIS_URL for cache, Celery and
# Django Channels, so every deployed process communicates through one Redis.
ENVIRONMENT = config("ENVIRONMENT", default="development").strip().lower()
# Render automatically provides RENDER=true at runtime. ENVIRONMENT remains
# useful for another production host, staging, or a local production test.
IS_RENDER = config("RENDER", default=False, cast=bool)
IS_PRODUCTION = IS_RENDER or ENVIRONMENT in {"production", "prod"}
REDIS_URL = config("REDIS_URL", default="").strip()

if IS_PRODUCTION:
    if not REDIS_URL:
        raise RuntimeError("REDIS_URL must be configured in production.")
    CACHE_REDIS_LOCATION = REDIS_URL
    CELERY_REDIS_LOCATION = REDIS_URL
    CHANNEL_REDIS_HOSTS = [REDIS_URL]
else:
    CACHE_REDIS_LOCATION = "redis://127.0.0.1:6379/1"
    CELERY_REDIS_LOCATION = "redis://127.0.0.1:6379/0"
    CHANNEL_REDIS_HOSTS = [("127.0.0.1", 6379)]

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': CACHE_REDIS_LOCATION,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'odozi',
    }
}

CELERY_BROKER_URL = CELERY_REDIS_LOCATION

CELERY_RESULT_BACKEND = CELERY_REDIS_LOCATION





# 1. Store the exact local file path configuration
PROJECT_ROOT = BASE_DIR.parent

PRIVATE_KEY_PATH = os.path.join(PROJECT_ROOT, "odozy-ci-agent.2026-05-17.private-key.pem")
# 2. Open and read the file text data into memory securely
if os.path.exists(PRIVATE_KEY_PATH):
    print("part66")
    with open(PRIVATE_KEY_PATH, "r", encoding="utf-8") as key_file:
        GITHUB_APP_PRIVATE_KEY = key_file.read()
else:
    # Fallback to prevent server crashes if the file isn't found locally
    GITHUB_APP_PRIVATE_KEY = ""



yaml_file_path = os.path.join(BASE_DIR, 'agents', 'orchestrator.yaml')


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    
    # Cookie configurations for the refresh token
    'AUTH_COOKIE': 'refresh_token',
    'AUTH_COOKIE_HTTPONLY': True,
    'AUTH_COOKIE_SECURE': True,       # True for HTTPS/Production/Loca.lt
    'AUTH_COOKIE_SAMESITE': 'Lax',     # Use 'None' if completely cross-domain
    "TOKEN_OBTAIN_SERIALIZER": "account_profile.serializers.OdoziCustomTokenSerializer"

}


ASGI_APPLICATION = 'odozi.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": CHANNEL_REDIS_HOSTS,
            "prefix": "odozi-asgi",
        },
    },
}
