# Generated by Django 6.0.5 on 2026-05-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0004_alter_workspacemembership_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_owner', models.CharField(max_length=255)),
                ('repo_full_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='account_profile.workspace')),
            ],
            options={
                'verbose_name': 'GitHub Repository',
                'verbose_name_plural': 'GitHub Repositories',
                'ordering': ['-updated_at'],
            },
        ),
    ]
