# Generated by Django 6.0.5 on 2026-05-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0006_rename_user_workspacemembership_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_value', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_profile.githubrepository')),
            ],
        ),
    ]
