# Generated by Django 6.0.5 on 2026-05-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0007_repositoryvariable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepositoryVariable',
        ),
    ]
