# Generated by Django 6.0.5 on 2026-05-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0008_delete_repositoryvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='branches_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='collaborators_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='contributors_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='repo_id',
            field=models.BigIntegerField(db_index=True, default=6756750, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='repo_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='repo_owner',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
