# Generated by Django 6.0.5 on 2026-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0009_githubrepository_branches_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='browser_family',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='encrypted_jwt_access_token',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='encrypted_jwt_refresh_token',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='expires_at_iso',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
