# Generated by Django 6.0.5 on 2026-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0010_userprofilemodel_browser_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='installation_id',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='installation_id',
            field=models.BigIntegerField(db_index=True, default=31252462444434, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workspacemembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('developer', 'Developer')], default='admin', max_length=20),
        ),
    ]
