# Generated by Django 6.0.5 on 2026-06-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0011_remove_workspace_installation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='installation_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
