# Generated by Django 6.0.5 on 2026-07-06 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0013_userllmconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='repo_full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='repo_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.RemoveField(
            model_name='githubrepository',
            name='workspace',
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='workspace',
            field=models.ManyToManyField(db_index=True, related_name='repositories', to='account_profile.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceRepositoryBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_profile.githubrepository')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_profile.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'repository'), name='unique_workspace_repository_link')],
            },
        ),
    ]
