# Generated by Django 6.0.5 on 2026-07-21 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0015_userprofilemodel_installed_github'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='repo_owner_db_relationship',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='REPO_OWNER', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
