# Generated by Django 6.0.5 on 2026-07-21 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0016_githubrepository_repo_owner_db_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='repo_owner_db_relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
