from urllib import response

from agents.orchestrator import start_agentic_workflow
import re
import json
import hmac
import hashlib
import time
import jwt
import requests


from django.shortcuts import get_object_or_404
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponseForbidden
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib.auth.models import User
from rest_framework import generics
from .models import UserProfileModel, Workspace, WorkspaceMembership
from odozi.utils.crypto import encrypt_token, decrypt_token
from agents.tasks import run_agentic_pipeline



def is_input_safe(user_text):
    # Block common shell injection characters
    forbidden_chars = [";", "&&", "||", ">", "<", "|", "$(", "{"]
    if any(char in user_text for char in forbidden_chars):
        return True
    return False






def verify_github_signature(request):
    # Get the signature from the header
    signature_header = request.headers.get('X-Hub-Signature-256')
    if not signature_header:
        return False
    
    # Calculate the expected signature using your secret
    # Ensure WEBHOOK_SECRET is in your settings.py
    hash_object = hmac.new(
        settings.WEBHOOK_SECRET.encode('utf-8'),
        msg=request.body,
        digestmod=hashlib.sha256
    )
    expected_signature = "sha256=" + hash_object.hexdigest()
    
    # Use hmac.compare_digest to prevent timing attacks
    return hmac.compare_digest(expected_signature, signature_header)


# ✅ FIX A: Restrict the endpoint securely to POST requests only
@csrf_exempt
@require_POST
def github_push_webhook(request):
    
    # A. Fetch the signature header generated by GitHub
    signature = request.headers.get('X-Hub-Signature-256')
    if not signature:
        return JsonResponse({"error": "Mising signature verification header"}, status=401)

    # B. Read your raw request body string bytes
    raw_payload_bytes = request.body

    # C. Calculate your own secure HMAC hash string using your private webhook password
    secret_key_bytes = settings.GITHUB_APP_CLIENT_SECRET.encode('utf-8')
    computed_hash = hmac.new(secret_key_bytes, raw_payload_bytes, hashlib.sha256).hexdigest()
    expected_signature = f"sha256={computed_hash}"

    # D. Compare them securely to prevent timing attacks
    if not hmac.compare_digest(signature, expected_signature):
        return JsonResponse({"error": "Invalid signature. Payload source untrusted."}, status=403)


    # 1. Parse the JSON body safely
    try:
        data = json.loads(request.body)
    except json.JSONDecodeError:
        return HttpResponseBadRequest("Invalid JSON payload structure")

    # 2. Extract verification headers
    event_type = request.headers.get('X-GitHub-Event')

    if event_type == 'push':
        # For a push, the branch is parsed out of the reference string
        # branch = data.get('ref', '').split('/')[-1]
        repo_url = data.get('repository', {}).get('clone_url')
        default_branch = data.get('repository', {}).get('default_branch', 'master')
        base_branch = default_branch

         # 3. Extract tracking variables from GitHub payload shape
        repo_data = data.get("repository", {})
        repo_name = repo_data.get("name")
        repo_owner = repo_data.get("owner", {}).get("login")
        
        # Extract commit hash and target branch reference string (e.g., "refs/heads/main")
        commit_sha = data.get("after") # The latest commit SHA that was pushed
        ref_string = data.get("ref", "")
        branch = ref_string.split("/")[-1] if ref_string else "main"
        
        # CRITICAL METADATA: This identifies which corporate app installation owns this repository
        installation_id = data.get("installation", {}).get("id")

        if not all([repo_name, repo_owner, commit_sha, installation_id]):
            return JsonResponse({"error": "Missing tracking metrics in payload structure"}, status=400)

        # ⚠️ MOCK MAPPING: In production, your AI agent / DB fetches what the user requested.
        # For this testing kickoff, we pass a default setup array.
        mock_user_rules = [
            {"rule_key": "check_auth", "params": {"function_prefix": "create", "decorator_name": "login_required"}},
            {"rule_key": "check_function_length", "params": {"keyword": "list", "max_lines": 1}}
        ]

        # 4. HAND OFF TO CELERY: Trigger Phase 2 asynchronously out of sight
        run_agentic_pipeline.delay( #type: ignore
            repo_owner=repo_owner,
            repo_name=repo_name,
            default_branch=default_branch,
            repo_data=repo_data,
            commit_sha=commit_sha,
            target_branch=branch,
            ref_string=ref_string,
            installation_id=134664223,
            user_requested_rules=mock_user_rules
        )

        return JsonResponse({"status": "queued", "commit": commit_sha, "branch": branch})
            
    elif event_type == 'pull_request':
        pr_data = data.get('pull_request', {})
        
        # Target branch for the merge proposal code context
        branch = pr_data.get('head', {}).get('ref')
        repo_url = data.get('repository', {}).get('clone_url')
        
        # ✅ FIX B: Fixed the deep object pathing for Pull Request base branch extraction
        base_branch = pr_data.get('base', {}).get('ref') or data.get('repository', {}).get('default_branch', 'main')
        
    else:
        return JsonResponse({"status": "ignored", "message": f"Event {event_type} not supported"}, status=200)

    # 3. Structural Field Validations
    if not repo_url or not branch:
        return JsonResponse({"error": "Missing repository tracking or reference tracking keys"}, status=400)

    # 4. Asynchronous Pipeline Triggers
    # Ensure start_agentic_workflow shifts computing workloads immediately off the view loop
    result = start_agentic_workflow(repo_url, branch, base_branch=base_branch)
    
    if result and result.get("status") == "error":
        return JsonResponse(result, status=400) 

    return JsonResponse({"status": "processing", "branch": branch})




def github_callback_view(request):
    # 1. Catch the 'code' parameter sent by GitHub in the URL query string
    code = request.GET.get('code')
    if not code:
        return JsonResponse({"error": "No authorization code returned from GitHub"}, status=400)
    installation_id = request.GET.get('installation_id')
    setup_action = request.GET.get('setup_action')
    print(installation_id, setup_action)
    # 2. Prepare the background request to trade the code for an Access Token
    # OAuth configuration credentials (keep your Client Secret in your settings.py env)
    client_id = "Iv23liUEbKH7D09scRIZ"
    # Read the variable safely from settings.py. If it's missing, default to an empty string.
    client_secret = getattr(settings, "GITHUB_APP_CLIENT_SECRET", "")
    print("client_secret", client_secret)  # Debugging line to confirm the value is being read correctly

    if not client_secret:
        return JsonResponse({"error": "Platform misconfiguration: GITHUB_APP_CLIENT_SECRET is missing from settings."}, status=500)
        
    token_url = "https://github.com/login/oauth/access_token"
    token_headers = {"Accept": "application/json"}
    token_payload = {
        "client_id": client_id,
        "client_secret": client_secret,
        "code": code,
        "redirect_uri": "http://127.0.0.1:8000/account/api/auth/github/callback/"
    }

    # Make the HTTP POST call to GitHub's token engine
    token_response = requests.post(token_url, json=token_payload, headers=token_headers)
    # print(token_response.status_code)
    # print(token_response.text)
    token_data = token_response.json()

    print("token_data", token_data)  # Debugging line to inspect the response from GitHub's token endpoint

    # Extract the token string
    access_token = token_data.get("access_token")
    if not access_token:
        return JsonResponse({"error": "Failed to exchange code for access token", "details": token_data}, status=400)

    # 3. Use the fresh token to fetch the user's basic profile details
    user_url = "https://api.github.com/user"
    user_headers = {
        "Authorization": f"Bearer {access_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    user_profile = requests.get(user_url, headers=user_headers).json()
    
    github_username = user_profile.get("login")
    github_email = user_profile.get("email")
    print("user_profile", user_profile)  # Debugging line to inspect the user profile data returned by GitHub

    # 4. Fallback if user's email is private (GitHub returns empty email if hidden)
    if not github_email:
        emails_url = "https://api.github.com/user/emails"
        emails_profile = requests.get(emails_url, headers=user_headers).json()
        # Find the primary verified email address from their list
                # ✅ DEFENSIVE FIX: Ensure emails_profile is an actual list before looping
        if isinstance(emails_profile, list):
            for email_entry in emails_profile:
                # ✅ DEFENSIVE FIX: Verify each item is a dict object, not a plain string error
                if isinstance(email_entry, dict):
                    if email_entry.get("primary") and email_entry.get("verified"):
                        github_email = email_entry.get("email")
                        break
        else:
            print(f"Warning: GitHub emails API did not return a valid list. Payload: {emails_profile}")


    if not github_username:
        return JsonResponse({"error": "Could not extract user details from profile"}, status=400)

    if installation_id:
        workspace, created = Workspace.objects.get_or_create(
            name = github_username,
                # Django searches the DB using these lookup fields:
            
            # If not found, Django creates it using lookup fields + these defaults:
            defaults={
                "installation_id": installation_id,
                "owner": request.user,
                "github_account_name": github_username,
            }
        )
        # workspace= Workspace.objects.create(name=company, owner=request.user, installation_id=installation_id, github_account_name=github_username)
        W_Membership= WorkspaceMembership.objects.create(role="admin", workspace=workspace, user=request.user)

    # 5. DB MANAGEMENT: Locate or create the user record in Django

    user, created = User.objects.get_or_create(
        username=github_username,
        defaults={
            "email": github_email or ""
        }
    )
    profile, _ = UserProfileModel.objects.get_or_create(
        user=user
    )

    profile.encrypted_access_token = encrypt_token(token_data.get("access_token"))
    profile.encrypted_refresh_token = encrypt_token(token_data.get("refresh_token"))
    profile.save()

    # Log the user into the active Django session layer
    login(request, user, backend='django.contrib.auth.backends.ModelBackend')

    # 6. SUCCESS: Send them back to your local frontend interface landing page
    # When using jQuery/Django Templates:
    return redirect("/dashboard/")
    
    # When using React later, change the line above to redirect to your React app port:
    # return redirect(f"http://localhost:3000/dashboard/?token={access_token}")





def revoke_developer_access(request, workspace_id, target_user_id):
    # 1. Enforce that only an active Admin of this specific workspace can execute a revoke command
    admin_membership = get_object_or_404(
        WorkspaceMembership, 
        workspace_id=workspace_id, 
        user=request.user, 
        role='admin', 
        is_active=True
    )
    
    # 2. Locate the targeted developer's membership row record
    dev_membership = get_object_or_404(
        WorkspaceMembership, 
        workspace_id=workspace_id, 
        user_id=target_user_id
    )
    
    # 3. Terminate access immediately by flipping the boolean status flag
    dev_membership.is_active = False
    dev_membership.save()
    
    return JsonResponse({"status": "success", "message": "Developer access successfully revoked."})



# @csrf_exempt
# @require_POST
# def github_installation_webhook(request):
#     """
#     Listens for real-time GitHub App installation events.
#     Creates the Workspace container and links the managing User.
#     """
#     # 1. Parse the incoming webhook body payload safely
#     try:
#         payload = json.loads(request.body)
#     except json.JSONDecodeError:
#         return HttpResponseBadRequest("Malformed JSON payload")

#     # 2. Verify this is explicitly an installation event step
#     event_type = request.headers.get('X-GitHub-Event')
#     if event_type != 'installation':
#         return JsonResponse({"status": "ignored", "message": f"Event {event_type} ignored by this endpoint"}, status=200)

#     action = payload.get("action")  # Can be "created", "deleted", or "suspend"
#     installation_data = payload.get("installation", {})
#     installation_id = installation_data.get("id")
    
#     # Extract the company organization or personal profile username account slot
#     account_data = installation_data.get("account", {})
#     print("account_data", account_data)  # Debugging line to inspect the account data structure returned by GitHub
#     print(" ")
#     print(" ")
#     print(payload,"payload")  # Debugging line to inspect the entire payload structure returned by GitHub
#     github_account_name = account_data.get("login") # e.g., "benmore-tech" or "semper44"

#     if not installation_id or not github_account_name:
#         return JsonResponse({"error": "Missing critical architectural metadata"}, status=400)

#     # =========================================================================
#     # ACTION: CREATED (The User completes Step 2 Installation)
#     # =========================================================================
#     if action == "created":
#         # Look up which Django user profile owns this matching GitHub handle
#         try:
#             target_user = User.objects.get(username=github_account_name)
#         except User.DoesNotExist:
#             # Fallback fallback safety: if testing, map it to the first user or log it
#             target_user = User.objects.first() 
#             if not target_user:
#                 return JsonResponse({"error": "No platform users exist to map this integration"}, status=404)

#         # Create or fetch the core organization workspace block container
#         workspace, ws_created = Workspace.objects.get_or_create(
#             installation_id=installation_id,
#             defaults={"name": github_account_name}
#         )

#         # Build or activate the member permission bridge mapping row
#         membership, mem_created = WorkspaceMembership.objects.get_or_create(
#             user=target_user,
#             workspace=workspace,
#             defaults={"role": "admin", "is_active": True}
#         )
        
#         # If they were previously fired/deleted, restore access cleanly
#         if not membership.is_active:
#             membership.is_active = True
#             membership.save()

#         return JsonResponse({"status": "installed", "workspace_id": workspace.id})

#     # =========================================================================
#     # ACTION: DELETED (The Company Sacks Odozi or Uninstalls it on GitHub)
#     # =========================================================================
#     elif action == "deleted":
#         # Instantly locate and tear down the workspace to protect privacy compliance boundaries
#         try:
#             workspace = Workspace.objects.get(installation_id=installation_id)
#             # This cascades and toggles off memberships automatically via models design rules
#             workspace.delete() 
#             return JsonResponse({"status": "uninstalled_cleanly"})
#         except Workspace.DoesNotExist:
#             return JsonResponse({"status": "already_purged"}, status=200)

#     return JsonResponse({"status": "ignored_action", "action": action})

