# Generated by Django 6.0.5 on 2026-07-04 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_profile', '0013_userllmconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository_name', models.CharField(max_length=255)),
                ('branch', models.CharField(default='master', max_length=100)),
                ('commit_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_profile.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AuditJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=50)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('execution_time_seconds', models.IntegerField(default=0)),
                ('log_blob_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='general.auditworkflow')),
            ],
        ),
    ]
