# Generated by Django 6.0.5 on 2026-08-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditjob',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='auditjob',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='auditjob',
            name='status',
        ),
        migrations.RemoveField(
            model_name='auditjob',
            name='tool_name',
        ),
        migrations.AddField(
            model_name='auditjob',
            name='report',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AuditWorkflow',
        ),
    ]
