# Generated by Django 6.0.5 on 2026-09-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_auditjob_workflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditjob',
            name='log_blob_path',
            field=models.CharField(blank=True, help_text='Path to the log blob in cloud storage', max_length=500, null=True),
        ),
    ]
