# Generated by Django 6.0.5 on 2026-09-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_auditjob_log_blob_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditjob',
            name='pipeline_id',
            field=models.UUIDField(db_index=True, default=253543, unique=True),
            preserve_default=False,
        ),
    ]
