# Generated by Django 6.0.5 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("general", "0004_auditjob_pipeline_id")]

    operations = [
        migrations.AlterField(
            model_name="auditjob",
            name="pipeline_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AddField(
            model_name="auditjob",
            name="run_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="auditjob",
            name="tool_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="auditjob",
            constraint=models.UniqueConstraint(
                fields=("pipeline_id", "tool_name", "run_id"),
                name="unique_auditjob_pipeline_tool_run",
            ),
        ),
        migrations.AddIndex(
            model_name="auditjob",
            index=models.Index(
                fields=["pipeline_id", "created_at"],
                name="general_aud_pipelin_03feb3_idx",
            ),
        ),
    ]
