# Generated by Django 6.0.5 on 2026-09-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auditjob_multiple_test_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditjob',
            name='history',
            field=models.CharField(default='heyy', max_length=500),
            preserve_default=False,
        ),
    ]
