# Generated by Django 6.0.5 on 2026-05-25 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_python', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('repo', models.CharField(max_length=255)),
                ('tool', models.CharField(choices=[('pytest', 'Pytest'), ('ruff', 'Ruff'), ('bandit', 'Bandit'), ('odozi_visitors', 'Odozi AST Engine')], max_length=50)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], default='passed', max_length=20)),
                ('total_issues', models.IntegerField(default=0)),
                ('high_severity_count', models.IntegerField(default=0)),
                ('lines_of_code', models.IntegerField(default=0)),
                ('structured_findings', models.JSONField(default=list)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_workspace', to='account_profile.Workspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
