# Generated by Django 6.0.5 on 2026-05-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_python', '0002_repositoryscan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryscan',
            name='user',
        ),
    ]
