# Generated by Django 6.0.5 on 2026-05-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_python', '0003_remove_repositoryscan_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repositoryscan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Repository Scan', 'verbose_name_plural': 'Repository Scans'},
        ),
        migrations.AlterField(
            model_name='repositoryscan',
            name='run_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='repositoryscan',
            unique_together={('run_id', 'tool')},
        ),
    ]
