# Generated by Django 6.0.5 on 2026-05-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0007_repositoryvariable'),
        ('django_python', '0004_alter_repositoryscan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoEnvKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_env_keys', to='account_profile.githubrepository')),
            ],
            options={
                'unique_together': {('repo', 'key_name')},
            },
        ),
    ]
