# Generated by Django 6.0.5 on 2026-07-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0015_userprofilemodel_installed_github'),
        ('django_python', '0006_chatsession_chatmessage_workflowrunhistory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repoenvkey',
            unique_together={('repo', 'key_name')},
        ),
        migrations.AddField(
            model_name='repoenvkey',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_env_keys', to='account_profile.workspace'),
        ),
        migrations.AlterField(
            model_name='repoenvkey',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repo_env_keys', to='account_profile.githubrepository'),
        ),
        migrations.AlterUniqueTogether(
            name='repoenvkey',
            unique_together={('repo', 'key_name'), ('workspace', 'key_name')},
        ),
    ]
