# Generated by Django 6.0.5 on 2026-09-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_python', '0007_alter_repoenvkey_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInputModel',
        ),
    ]
